In [1]:
import numpy as np

In [2]:
X = np.array([[0.75, 0.80],
              [0.20, 0.05],
              [-0.75, 0.8],
              [0.2, -0.05]])

W1 = np.array([[0.6, 0.7, 0],
               [0.01, 0.43, 0.88]])

W2 = np.array([[0.02],[0.03],[0.09]])

Y = np.array([[1], [1], [-1], [-1]])

In [5]:
print(X + np.asarray([[1,2]]))

[[ 1.75  2.8 ]
 [ 1.2   2.05]
 [ 0.25  2.8 ]
 [ 1.2   1.95]]


In [3]:
#ReLu
def f(x):
    return np.maximum(x,0)
#ReLu derivative
def f_p(x):
    x2 = x.copy()
    x2[np.where(x2 > 0)] = 1
    x2[np.where(x2 < 0)] = 0
    
    return x2

In [4]:
S1 = np.dot(X,W1)
Z1 = f(S1)

print(Z1)

[[ 0.458   0.869   0.704 ]
 [ 0.1205  0.1615  0.044 ]
 [ 0.      0.      0.704 ]
 [ 0.1195  0.1185  0.    ]]


In [5]:
S2 = np.dot(Z1, W2)
Z2 = S2
Y_out = Z2

print(Z2)

[[ 0.09859 ]
 [ 0.011215]
 [ 0.06336 ]
 [ 0.005945]]


In [6]:
L = 0.5 * np.power(Y_out - Y,2)
np.sum(L)

1.9664477984750004

In [7]:
#d_out = np.multiply((Y_out - Y),f_p(S2))
d_out = np.multiply((Y_out - Y),1)

print(d_out)

[[-0.90141 ]
 [-0.988785]
 [ 1.06336 ]
 [ 1.005945]]


In [8]:
d_1 = f_p(S1) * np.dot(W2, d_out.T).T
print(d_1)

[[-0.0180282  -0.0270423  -0.0811269 ]
 [-0.0197757  -0.02966355 -0.08899065]
 [ 0.          0.          0.0957024 ]
 [ 0.0201189   0.03017835  0.        ]]


In [131]:
dW1 = np.dot(X.T , d_1) #/ X.shape[0] 
print(dW1)

[[ 0.03574254  0.0586202   0.01701347]
 [-0.0242163  -0.02310964 -0.06372963]]


In [124]:
dW2 = np.dot(Z1.T , d_out) #/ X.shape[0]
print(dW2)

[[ 0.00589448]
 [-0.0441525 ]
 [ 0.01659295]]


In [125]:
a = 0.5

W1 = W1 - a * dW1
W2 = W2 - a * dW2